yatube/about/urls.py
from django.urls import path

from . import views

app_name = 'about'

urlpatterns = [
    path('author/', views.AboutAuthorView.as_view(), name='author'),
    path('tech/', views.AboutTechView.as_view(), name='tech'),
]

yatube/posts/urls.py
from django.urls import path

from . import views

# app_name = 'posts'

urlpatterns = [
    path("", views.index, name="index"),
    path("new/", views.new_post, name="new_post"),
    path("group/", views.group_list, name="group_list"),
    path("user/", views.users_list, name="user_list"),
    path("group/<slug:slug>/", views.group_posts, name="group_posts"),
    path('<str:username>/', views.profile, name='profile'),
    path('<str:username>/<int:post_id>/', views.post_view, name='post'),
    path('<str:username>/<int:post_id>/edit/', views.post_edit,
         name='post_edit'),
]

yatube/users/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('signup/', views.SignUp.as_view(), name='signup')
]

yatube/yatube/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('auth/', include('users.urls')),
    path('auth/', include('django.contrib.auth.urls')),
    path('about/', include('about.urls', namespace='about')),
    path("", include("posts.urls")),
]

yatube/posts/models.py
from django.db import models
from django.contrib.auth import get_user_model

User = get_user_model()


class Group(models.Model):
    title = models.CharField(max_length=200)
    slug = models.SlugField(unique=True)
    description = models.TextField()

    def __str__(self):
        return self.title


class Post(models.Model):
    text = models.TextField()
    pub_date = models.DateTimeField("date published", auto_now_add=True)
    author = models.ForeignKey(User, on_delete=models.CASCADE,
                               related_name="posts")
    group = models.ForeignKey(Group, on_delete=models.SET_NULL,
                              related_name="posts", blank=True, null=True)

    def __str__(self):
        return self.text[:15]

    class Meta:
        ordering = ['-pub_date']

yatube/posts/forms.py
from django import forms
from .models import Post


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ["text", "group"]
        help_texts = {
            "text": "Здесь должен быть текст поста",
            "group": "А здесь можно выбрать группу для опубликования"
        }
        labels = {
            "text": "Текст поста",
            "group": "Группа"
        }

yatube/users/forms.py
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import get_user_model


User = get_user_model()


class CreationForm(UserCreationForm):
    class Meta(UserCreationForm.Meta):
        model = User
        fields = ('first_name', 'last_name', 'username', 'email')

yatube/about/views.py
from django.views.generic.base import TemplateView


class AboutTechView(TemplateView):
    template_name = 'about/tech.html'


class AboutAuthorView(TemplateView):
    template_name = 'about/author.html'

yatube/posts/views.py
from .forms import PostForm
from django.shortcuts import render, get_object_or_404, redirect
from django.core.paginator import Paginator
from .models import Group, Post, User
from django.contrib.auth.decorators import login_required


def index(request):
    post_list = Post.objects.all()
    paginator = Paginator(post_list, 10)
    page_number = request.GET.get('page')
    page = paginator.get_page(page_number)
    return render(request,
                  'index.html',
                  {'page': page, }
                  )


def group_posts(request, slug):
    group = get_object_or_404(Group, slug=slug)
    post_list = group.posts.all()
    paginator = Paginator(post_list, 10)
    page_number = request.GET.get('page')
    page = paginator.get_page(page_number)
    return render(request, "group.html", {"group": group, "page": page})


@login_required
def group_list(request):
    groups = Group.objects.all()
    return render(request, "groups_list.html", {"groups": groups})


def profile(request, username):
    user = get_object_or_404(User, username=username)
    post_list = user.posts.all()
    paginator = Paginator(post_list, 10)
    post_count = paginator.count
    page_number = request.GET.get('page')
    page = paginator.get_page(page_number)
    content = {
        "user_post": user,
        "page": page,
        "post_count": post_count
    }
    return render(request, 'profile.html', content)


def post_view(request, username, post_id):
    post = get_object_or_404(Post, pk=post_id, author__username=username)
    user = post.author
    "Я, честно, его уже 2 раза писал как count()"
    post_count = user.posts.count()
    content = {
        "user_post": user,
        "post": post,
        "post_count": post_count
    }
    return render(request, 'post.html', content)


def users_list(request):
    users = User.objects.all()
    return render(request, "users_list.html", {"users": users})


@login_required
def new_post(request):
    form = PostForm(request.POST or None)
    if form.is_valid():
        post = form.save(commit=False)
        post.author = request.user
        post.save()
        return redirect("/")
    return render(request, "new_post.html", {"form": form})


@login_required
def post_edit(request, username, post_id):
    post = get_object_or_404(Post, author__username=username, pk=post_id)
    if request.user != post.author:
        return redirect("/")
    form = PostForm(request.POST or None, instance=post)
    if form.is_valid():
        form.save()
        return redirect("post", username=username, post_id=post_id)
    return render(request, "post_edit.html", {"form": form})

yatube/users/views.py
from django.views.generic import CreateView
from django.urls import reverse_lazy
from .forms import CreationForm


class SignUp(CreateView):
    form_class = CreationForm
    success_url = reverse_lazy('login')
    template_name = "signup.html"

yatube/templates/about/author.html
<!-- templates/about/author.html -->
{% extends "base.html" %}
{% block title %}Об авторе проекта{% endblock %}
{% block content %}
  <div class="row">
    <!-- Левый вспомогательный блок -->
    <div class="col-md-3 mb-3 mt-1">
      <div class="card">
        <div class="card-body">
          <ul class="list-group list-group-flush">
            <li class="list-group-item">
              <div class="h3">
                Об авторе
              </div>
            </li>
            <li class="list-group-item">
              <div class="h6 text-muted">
                Статен <br>
                Красив <br>
                Умен <br>
                Холост <br>
              </div>
            </li>
          </ul>
        </div>
      </div>
    </div>
    <!-- Тело страницы -->
    <div class="col-md-9">
      <div class="card-body">
        <div class="card-text">
          <p>Автору проекта не хватает времени, но он все равно сделал эту страницу</p>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

yatube/templates/about/tech.html
<!-- templates/about/author.html -->
{% extends "base.html" %}
{% block title %}Об авторе проекта{% endblock %}
{% block content %}
  <div class="row">
    <!-- Левый вспомогательный блок -->
    <div class="col-md-3 mb-3 mt-1">
      <div class="card">
        <div class="card-body">
          <ul class="list-group list-group-flush">
            <li class="list-group-item">
              <div class="h3">
                О технологиях
              </div>
            </li>
            <li class="list-group-item">
              <div class="h6 text-muted">
                Python 3.7 <br>
                Django 2.2
              </div>
            </li>
          </ul>
        </div>
      </div>
    </div>
    <!-- Тело страницы -->
    <div class="col-md-9">
      <div class="card-body">
        <div class="card-text">
          <p>Python 3.7 <br>
            Django 2.2</p>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

yatube/templates/base.html
<!doctype html>
<html>

  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>{% block title %}The Last Social Media You'll Ever Need{% endblock %} | Yatube</title>
    <!-- Загрузка статики -->
    {% load static %}
    <link rel="stylesheet" href="{% static 'bootstrap/dist/css/bootstrap.min.css' %}">
    <script src="{% static 'jquery/dist/jquery.min.js' %}"></script>
    <script src="{% static 'bootstrap/dist/js/bootstrap.min.js' %}"></script>
  </head>

  <body>
    {% include 'includes/nav.html' %}
    <main>
      <div class="container">
        <h1>{% block header %}The Last Social Media You'll Ever Need{% endblock %}</h1>
        <p>{% block description %}
          <!-- Описание страницы -->
        {% endblock %}
        </p>
        <!-- Либо все писать в "content"
        либо в "left-content" и "right-content" -->
        {% block content %}
          <div class="row">
            <div class="col-12 col-md-3">
                {% block left-content %}
                {% endblock %} 
            </div>
            <div class="col-12 col-md-9">
                {% block right-content %}
                {% endblock %} 
            </div>
          </div> 
        {% endblock %}
          
      </div>
    </main>
  {% include 'includes/footer.html' %}
  </body>

</html> 

yatube/templates/group.html
{% extends "base.html" %}
{% block title %}Записи сообщества {{ group.title }}{% endblock %}
{% block header %}{{ group.title }}{% endblock %}
{% block description %}{{ group.description }}{% endblock %}
{% block content %}

{% for post in page %}
<h3>
  Автор: {{ post.author.get_full_name }}, Дата публикации: {{ post.pub_date|date:"d M Y" }}
</h3>
<p>{{ post.text|linebreaksbr }}</p>
{% if not forloop.last %}<hr>{% endif %}
{% endfor %}
{% include "includes/paginator.html" %}
  <br><br><h3><a href=".">Список сообществ</a></h3>
{% endblock %} 

yatube/templates/groups_list.html
{% extends "base.html" %}
{% block title %}Список сообществ {% endblock %}
{% block header %}Сообщества{% endblock %}
{% block description %} {% endblock %}
{% block content %}

  {% for group in groups %}
    <h3>
      <a href="{{ group.slug }}">{{ group.title }}</a>
    </h3>

  {% endfor %}

{% endblock %} 

yatube/templates/includes/author_card.html
<div class="container">
  <div class="card">
    <div class="card-header">
      <h1><a href="{% url 'profile' user_post.username %}">@{{ user_post.username }}</a></h1>
      <h3>{{ user_post.first_name }} {{ user_post.last_name }}</h3>
    </div>
    <div class="card-body">
      Подписчиков: XXX <br>
      Подписан: XXX <br>
      Публикаций: {{ post_count }}
    </div>
  </div>
</div>

yatube/templates/includes/footer.html
<!-- Шаблон footer.html -->
<footer class="pt-4 my-md-5 pt-md-5 border-top">
  <p class="m-0 text-dark text-center ">
    <a href="{% url 'about:author' %}">Об авторе</a>
    <a href="{% url 'about:tech' %}">О технологиях</a>
  </p>
  <p class="m-0 text-dark text-center ">
    Социальная сеть <span style="color:red">Ya</span>tube
  </p>
</footer> 

yatube/templates/includes/nav.html
<nav class="navbar navbar-light" style="background-color: #e3f2fd;">
    <a class="navbar-brand" href="/"><span style="color:red">Ya</span>tube</a>
    <a href="/new">Новый пост</a>
    <nav class="my-2 my-md-0 mr-md-3">
      {% if user.is_authenticated %}
        Пользователь: {{ user.username }}.
        <a class="p-2 text-dark" href="{% url 'password_change' %}">Изменить пароль</a>
        <a class="p-2 text-dark" href="{% url 'logout' %}">Выйти</a>
      {% else %}
        <a class="p-2 text-dark" href="{% url 'login' %}">Войти</a> |
        <a class="p-2 text-dark" href="{% url 'signup' %}">Регистрация</a>
      {% endif %}
    </nav>
  </nav> 

yatube/templates/includes/paginator.html
{# Отрисовываем навигацию паджинатора только если все посты не помещаются на первую страницу, если есть другие страницы #}
    {% if page.has_other_pages %}
      <nav>
        <ul class="pagination">
          {% if page.has_previous %}
            <li class="page-item">
              <a
                class="page-link"
                href="?page={{ page.previous_page_number }}">&laquo; Предыдущая</a>
            </li>
          {% else %}
            <li class="page-item disabled">
              <span class="page-link">&laquo; Предыдущая</span>
            </li>
          {% endif %}
          {% for i in page.paginator.page_range %}
            {% if page.number == i %}
              <li class="page-item active">
                <span class="page-link">{{ i }}
                  <span class="sr-only">(текущая)</span>
                </span>
              </li>
            {% else %}
              <li class="page-item">
                <a class="page-link" href="?page={{ i }}">{{ i }}</a>
              </li>
            {% endif %}
          {% endfor %}
          {% if page.has_next %}
            <li class="page-item">
              <a
                class="page-link"
                href="?page={{ page.next_page_number }}">Следующая &raquo;</a>
            </li>
          {% else %}
            <li class="page-item disabled">
              <span class="page-link">Следующая &raquo;</span>
            </li>
          {% endif %}
        </ul>
      </nav>
    {% endif %}

yatube/templates/includes/post_card.html
<div class="card">
  <h5 class="card-header">
    <!-- Нет, это не часть шаблона author_card, это просто заголовок поста, каждого в отдельности  -->
    Автор: @{{ post.author.username }}, Дата публикации: {{ post.pub_date|date:"d M Y" }}
  </h5>
  <div class="card-body">
    <p>{{ post.text|linebreaksbr }}</p>
    <!-- Ссылка на страницу записи в атрибуте href-->
    {% if user.is_authenticated %}
      <a class="btn btn-sm btn-primary" href="{% url 'post' username=post.author post_id=post.pk %}" role="button">
          Добавить комментарий
      </a>
    {% endif %}
      <!-- Ссылка на редактирование, показывается только автору записи.
        Эту ссылку вы подключите в финальном задании спринта -->
      {% if post.author == user %}
      <a class="btn btn-sm btn-primary" href="{% url 'post_edit' username=post.author post_id=post.pk %}" role="button">
        Редактировать
      </a>
      {% endif %}
    
  </div>
</div>

yatube/templates/index.html
{% extends "base.html" %}
{% block title %}Последние обновления на сайте{% endblock %}
{% block header %}
<a href="{% url 'group_list' %}">Список сообществ</a><br>
<a href="{% url 'user_list' %}">Список пользователей</a><br><br>
Последние обновления на сайте
{% endblock %}
{% block content %}
  
  {% for post in page %}
    {% include 'includes/post_card.html' %}
  {% endfor %}
  {% include "includes/paginator.html" %}
  
{% endblock %} 

yatube/templates/new_post.html
{% extends "base.html" %}
{% block title %}Новый пост{% endblock %}
{% block header %}{% endblock %}

{% block content %}

  <div class="row justify-content-center">
    <div class="col-md-8 p-5">
      <div class="card">
        <div class="card-header">{% block post_titile %}Новый пост{% endblock %}</div>
        <div class="card-body">

          {% for error in form.errors %}
            <div class="alert alert-danger" role="alert">
              {{ error }}
            </div>
          {% endfor %}

          <form method="post">
            {% csrf_token %}
            {% for field in form %}
              <div class="form-group row" aria-required={{ field.field.required }}>
                <label
                  for="{{ field.id_for_label }}"
                  class="col-md-4 col-form-label text-md-right">
                  {{ field.label }}
                  {% if field.field.required %}
                    <span class="required">*</span>
                  {% endif %}
                </label>
                <div class="col-md-6">
                  {# подключаем фильтр и указываем класс #}
                  {{ field }}
                  {% if field.help_text %}
                    <small
                      id="{{ field.id_for_label }}-help"
                      class="form-text text-muted">
                      {{ field.help_text|safe }}
                    </small>
                  {% endif %}
                </div>
              </div>
            {% endfor %}

            <div class="col-md-6 offset-md-4">
              <button type="submit" class="btn btn-primary">
                {% block button %}Опубликовать{% endblock %}
              </button>
            </div>
          </form>
        </div> <!-- card body -->
      </div> <!-- card -->
    </div> <!-- col -->
  </div> <!-- row -->

{% endblock %}

yatube/templates/post.html
{% extends "base.html" %}
{% block title %}Профиль {{ user_post.username }}{% endblock %}
{% block header %}
     
{% endblock %}
{% block left-content %}{% include "includes/author_card.html" %}{% endblock %}

{% block right-content %}

    {% include 'includes/post_card.html' %}

{% endblock %}

yatube/templates/post_edit.html
{% extends "new_post.html" %}
{% block post_titile %}Изменить пост{% endblock %}
{% block button %}Отредактировать{% endblock %}

yatube/templates/profile.html
{% extends "base.html" %}
{% block title %}Профиль {{ user_post.username }}{% endblock %}
{% block header %}{% endblock %}
{% block description %}{% endblock %}

{% block left-content %}
  {% include "includes/author_card.html" %}
{% endblock %} 

{% block right-content %}
  {% for post in page %}
  {% include 'includes/post_card.html' %}
  {% endfor %}
  {% include "includes/paginator.html" %}
  
{% endblock %} 

yatube/templates/test.html
<!DOCTYPE html>
<html lang="ru">
  <head>
    <!-- Другие мета-теги тут -->
    <!-- Подключили адаптивность  -->
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- Подключили CSS-файл Bootstrap -->
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-+0n0xVW2eSR5OomGNYDnhzAbDsOXxcvSN1TPprVMTNDbiYZCxYbOOl7+AMvyTG2x"
      crossorigin="anonymous">
    <!-- После стилевого файла Bootstrap можно
         написать собственные стили в теге <style> -->
    <!-- А лучше подключить свой CSS-файл и описать свои стили в нём:
        <link rel="stylesheet" href="css/style.css"> -->
    <style>
      .card {
        background: #eee;
        box-shadow: rgb(0 0 0 / 20%) 2px 2px 5px;
      }
    </style>
  </head>
  <body>

    <!-- Классы Bootstrap можно применять и к семантическим блокам. -->
    <div class="container">

      <!-- Начало глобального div.row с двумя колонками: 
       в левой колонке - имена авторов, в правой - блоки с текстом -->
      <div class="row">

        <!-- Начало левой колонки сайта со списком авторов -->
        <aside class="col-12 col-md-3">
          <ul class="list-group">
            <li class="list-group-item">Аксентий Поприщин</li>
            <li class="list-group-item">Робинзон Крузо</li>
            <li class="list-group-item">Чарли Гордон</li>
            <li class="list-group-item">Владимир Высоцкий</li>
          </ul>
        </aside>
        <!-- Конец левой колонки сайта -->

        <!-- Начало правой (широкой) колонки сайта -->
        <section class="col-12 col-md-9">

          <!-- Можно разбить на колонки содержимое любого блока.
           В этом div.row созданы четыре колонки с анонсами постов -->
          <div class="row">

            <!-- Начало первой колонки -->
            <article class="col-12 col-md-6 col-xl-3">
              <div class="card">
                <h5 class="card-header">Аксентий Поприщин</h5>
                <div class="card-body">
                  <h6 class="card-subtitle">Число 25</h6>
                  <p>
                    Сегодня великий инквизитор пришел в мою комнату, но я,
                    услышавши еще издали шаги его, спрятался под стул.
                  </p>
                  <a href="" class="btn btn-primary">Читать целиком</a>
                </div>
              </div>
            </article>
            <!-- Конец первой колонки -->

            <!-- Начало второй колонки -->
            <article class="col-12 col-md-6 col-xl-3">
              <div class="card">
                <h5 class="card-header">Робинзон Крузо</h5>
                <div class="card-body">
                  <h6 class="card-subtitle">25 октября 1659 года</h6>
                  <p>
                    Шквальный ветер сотрясал остров целую ночь,
                    а наутро я увидел, что наш корабль разнесло в щепки.
                  </p>
                  <a href="" class="btn btn-primary">Читать целиком</a>
                </div>
              </div>
            </article>
            <!-- Конец второй колонки -->

            <!-- Начало третьей колонки -->
            <article class=" col-12 col-md-6 col-xl-3">
              <div class="card">
                <h5 class=" card-header">Чарли Гордон</h5>
                <div class="card-body">
                  <h6 class="card-subtitle">1 атчет 3 марта</h6>
                  <p>
                    Док Штраус сказал што я должен писать все што я думаю и
                    помню и все што случаеца со мной с севодня. Я не знаю
                    пачему но он гаварит што это важно штобы они могли
                    увидить што я падхажу им.
                  </p>
                  <a href="" class="btn btn-primary">Читать целиком</a>
                </div>
              </div>
            </article>
            <!-- Конец третьей колонки -->

            <!-- Начало четвёртой колонки -->
            <article class=" col-12 col-md-6 col-xl-3">
              <div class="card">
                <h5 class=" card-header">Владимир Высоцкий</h5>
                <div class="card-body">
                  <h6 class="card-subtitle">3 апреля 1976 года</h6>
                  <p>
                    Если б Кащенко, к примеру, лёг лечиться к Пирогову -
                    Пирогов бы без причины резать Кащенку не стал…
                  </p>
                  <a href="" class="btn btn-primary">Читать целиком</a>
                </div>
              </div>
            </article>
            <!-- Конец четвёртой колонки -->
          </div>  <!-- Конец вложенного div.row -->

        </section>  <!-- Конец правой (широкой) колонки сайта -->
      </div>  <!-- Конец div.row  -->
    </div>  <!-- Конец div.container -->
  </body>
</html> 

yatube/templates/users_list.html
{% extends "base.html" %}
{% block title %}Список пользователей {% endblock %}
{% block header %}Пользователи{% endblock %}
{% block description %} {% endblock %}
{% block content %}

  {% for user in users %}
    <h3>
      <a href="/{{ user.username }}">{{ user.first_name }} {{ user.last_name }}</a>
    </h3>

  {% endfor %}

{% endblock %} 

yatube/users/templates/signup.html
{% extends "base.html" %}
{% block title %}Зарегистрироваться{% endblock %}
{% block content %}
  {# загружаем фильтр #}
  {% load user_filters %}

  <div class="row justify-content-center">
    <div class="col-md-8 p-5">
      <div class="card">
        <div class="card-header">Зарегистрироваться</div>
        <div class="card-body">

          {% for error in form.errors %}
            <div class="alert alert-danger" role="alert">
              {{ error }}
            </div>
          {% endfor %}

          <form method="post" action="{% url 'signup' %}">
            {% csrf_token %}
            {% for field in form %}
              <div class="form-group row" aria-required={{ field.field.required }}>
                <label
                  for="{{ field.id_for_label }}"
                  class="col-md-4 col-form-label text-md-right">
                  {{ field.label }}
                  {% if field.field.required %}
                    <span class="required">*</span>
                  {% endif %}
                </label>
                <div class="col-md-6">
                  {# подключаем фильтр и указываем класс #}
                  {{ field|addclass:"form-control" }}
                  {% if field.help_text %}
                    <small
                      id="{{ field.id_for_label }}-help"
                      class="form-text text-muted">
                      {{ field.help_text|safe }}
                    </small>
                  {% endif %}
                </div>
              </div>
            {% endfor %}

            <div class="col-md-6 offset-md-4">
              <button type="submit" class="btn btn-primary">
                Зарегистрироваться
              </button>
            </div>
          </form>
        </div> <!-- card body -->
      </div> <!-- card -->
    </div> <!-- col -->
  </div> <!-- row -->

{% endblock %}